---
- name: Install df dependancies
  sudo: yes
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - libgtk2.0-0
    - libglu1-mesa
    - libsdl1.2debian
    - libsdl-image1.2
    - libsdl-ttf2.0-0
    - libopenal1
  tags: install

- name: Fetch DF
  get_url: url=http://www.bay12games.com/dwarves/df_43_05_linux.tar.bz2
           dest=/df_linux.tar.bz2
  tags: install

- name: Decompress DF
  unarchive: src=/df_linux.tar.bz2 dest=/ copy=no
  tags:
    - install
    - reset

- name: Add dwarffortress launcher
  get_url: url=https://raw.githubusercontent.com/bencawkwell/launch_df/v0.3.1/dwarffortress
           dest=/bin/dwarffortress
           mode=0755
  tags:
    - install
    - reset

- name: Add empty dwarffortress.conf to /etc
  file: dest=/etc/dwarffortress.conf
        state=touch
  tags:
    - install
    - reset

- name: Change permissions of /df_linux to be owned by df user
  file: path=/df_linux
        recurse=yes
        owner=df
        group=df
  tags:
    - install
    - reset