---
- name: Fetch DFHack
  get_url: url=https://github.com/DFHack/dfhack/releases/download/0.43.05-alpha4/dfhack-0.43.05-alpha4-Linux-64-gcc-4.8.1.tar.bz2
           dest=/dfhack.tar.bz2
  tags: install

- name: Decompress DFHack
  unarchive: src=/dfhack.tar.bz2 dest=/df_linux copy=no
  tags:
    - install
    - reset

- name: Set dfhack in /etc/dwarffortress.conf
  lineinfile: dest=/etc/dwarffortress.conf
              regexp='^df_launcher(.*)$'
              line='df_launcher=dfhack'
              state=present
  tags:
    - reset
    - configure

- name: Copy dfhack.init-example to dfhack.init
  command: cp /df_linux/dfhack.init-example /df_linux/dfhack.init
  tags:
    - reset
    - configure

- name: Change permissions of /df_linux to be owned by df user
  file: path=/df_linux
        recurse=yes
        owner=df
        group=df
  tags:
    - install
    - reset