---
- name: Fetch Tile Set GemSet
  get_url: url=https://github.com/DFgraphics/GemSet/archive/master.zip
           dest=/GemSet.zip
  tags: install

- name: create GemSet directory
  file: path=/GemSet
        state=directory
        mode=0755
  tags:
    - install
    - reset

- name: Decompress Tile Set GemSet
  unarchive: src=/GemSet.zip
             dest=/GemSet
             copy=no
  tags:
    - install
    - reset

- name: Copy over GemSet raw
  shell: cp -ar /GemSet/GemSet-*/raw /df_linux/
  tags:
    - reset
    - configure

- name: Copy GemSet art to data/
  shell: cp -ar /GemSet/GemSet-*/data/art /df_linux/data/
  tags:
    - reset
    - configure

- name: Copy GemSet colors.txt to data/init/
  shell: cp -ar /GemSet/GemSet-*/data/init/colors.txt /df_linux/data/init/colors.txt
  tags:
    - reset
    - configure

- name: Copy GemSet d_init.txt to data/init/
  shell: cp -ar /GemSet/GemSet-*/data/init/d_init.txt /df_linux/data/init/d_init.txt
  tags:
    - reset
    - configure

- name: Copy GemSet overrides.txt to data/init/
  shell: cp -ar /GemSet/GemSet-*/data/init/overrides.txt /df_linux/data/init/overrides.txt
  tags:
    - reset
    - configure

- name: Set init.txt FONT to GemSet
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[FONT\:(.*)$'
              line=[FONT:Jecobus_10x16.png]
              state=present
              backrefs=yes
  tags: configure

- name: Set init.txt FULLFONT to GemSet
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[FULLFONT\:(.*)$'
              line=[FULLFONT:Jecobus_10x16.png]
              state=present
              backrefs=yes
  tags: configure

- name: Set init.txt GRAPHICS to YES
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[GRAPHICS\:(.*)$'
              line=[GRAPHICS:YES]
              state=present
              backrefs=yes
  tags: configure

- name: Set init.txt GRAPHICS_FONT to GemSet
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[GRAPHICS_FONT\:(.*)$'
              line=[GRAPHICS_FONT:GemSet_16x16.png]
              state=present
              backrefs=yes
  tags: configure

- name: Set init.txt GRAPHICS_FULLFONT to GemSet
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[GRAPHICS_FULLFONT\:(.*)$'
              line=[GRAPHICS_FULLFONT:GemSet_16x16.png]
              state=present
              backrefs=yes
  tags: configure

- name: Set init.txt TRUETYPE to YES
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[TRUETYPE\:(.*)$'
              line=[TRUETYPE:YES]
              state=present
              backrefs=yes
  tags: configure

- name: Change permissions of /df_linux to be owned by df user
  file: path=/df_linux
        recurse=yes
        owner=df
        group=df
  tags:
    - install
    - reset