---
- name: Install general dependancies
  sudo: yes
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - curl
    - tar
    - bzip2
    - git
    - unzip
  tags: install

- name: Ensure df group exist
  group: name=df gid=14503 state=present
  sudo: yes
  tags:
  - install

- name: Ensure df user exist
  user: name=df uid=14503 group=df state=present
  sudo: yes
  tags:
  - install