---
- name: Fetch Tile Set spacefox
  get_url: url=https://github.com/DFgraphics/Spacefox/archive/43.05f.zip
           dest=/spacefox.zip
  tags: install

- name: create spacefox directory
  file: path=/spacefox
        state=directory
        mode=0755
  tags:
    - install
    - reset

- name: Decompress Tile Set spacefox
  unarchive: src=/spacefox.zip
             dest=/spacefox
             copy=no
  tags:
    - install
    - reset

- name: Copy over spacefox raw
  shell: cp -ar /spacefox/spacefox-*/raw /df_linux/
  tags:
    - reset
    - configure

- name: Copy spacefox art to data/
  shell: cp -ar /spacefox/spacefox-*/data/art /df_linux/data/
  tags:
    - reset
    - configure

- name: Copy spacefox init to data/init/
  shell: cp -ar /spacefox/spacefox-*/data/init /df_linux/data/
  tags:
    - reset
    - configure

- name: Change permissions of /df_linux to be owned by df user
  file: path=/df_linux
        recurse=yes
        owner=df
        group=df
  tags:
    - install
    - reset